# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: chickenapp.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_10DC1C6B9F1142C393120401585F5CE8 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_91B2FFD513924396896A8BFADD175DEB }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: chickenapp.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_10DC1C6B9F1142C393120401585F5CE8 }}/chicken:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A6FF020C42904C2B898373FB000B8D7A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56EB32691AA04F54B8D6B6F7C50960A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1FC0C60915714B02957ED8AE6FB9037A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chickenapp'
          slot-name: 'Production'
          images: 'chickenapp.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_10DC1C6B9F1142C393120401585F5CE8 }}/chicken:${{ github.sha }}'
          